export const buttonMap = {
  1: "#number1",
  2: "#number2",
  3: "#number3",
  4: "#number4",
  5: "#number5",
  6: "#number6",
  7: "#number7",
  8: "#number8",
  9: "#number9",
  0: "#number0",
  "+": "#operator-add",
  "-": "#operator-subtract",
  "/": "#operator-divide",
  "*": "#operator-multiply",
  "=": "#operator-equals",
};
